// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPXlU6vBwcZnOb898mbhOZtDIcuYBc3ho',
    appId: '1:236162384586:web:fb8074e08f58118a2d6a33',
    messagingSenderId: '236162384586',
    projectId: 'fineye-app',
    authDomain: 'fineye-app.firebaseapp.com',
    storageBucket: 'fineye-app.firebasestorage.app',
    measurementId: 'G-0CS7F6PFRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeuOQBt9ow8xYu3PR55E-QJx3EPFIwW4A',
    appId: '1:236162384586:android:abd67a3922feae2e2d6a33',
    messagingSenderId: '236162384586',
    projectId: 'fineye-app',
    storageBucket: 'fineye-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwN-_WiAZFOrZnOYr_hYEb3GvfOC-RAY',
    appId: '1:236162384586:ios:a2ae5969b25575732d6a33',
    messagingSenderId: '236162384586',
    projectId: 'fineye-app',
    storageBucket: 'fineye-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVwN-_WiAZFOrZnOYr_hYEb3GvfOC-RAY',
    appId: '1:236162384586:ios:a2ae5969b25575732d6a33',
    messagingSenderId: '236162384586',
    projectId: 'fineye-app',
    storageBucket: 'fineye-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPXlU6vBwcZnOb898mbhOZtDIcuYBc3ho',
    appId: '1:236162384586:web:a4f6290d86b83b452d6a33',
    messagingSenderId: '236162384586',
    projectId: 'fineye-app',
    authDomain: 'fineye-app.firebaseapp.com',
    storageBucket: 'fineye-app.firebasestorage.app',
    measurementId: 'G-GGZ6X5YFE8',
  );

}